spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/user_db?serverTimezone=UTC&useSSL=false
    username: root
    password: 1qaz@WSX
    driver-class-name: com.mysql.jdbc.Driver
    # Hikari 连接池配置
    hikari:
      # 最小空闲链接
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
  aop:
    proxy-target-class: true


server:
  port: 8090

#集成mybatis
mybatis:
  #xml路径
  mapper-locations: classpath:mapper/**.xml
  #pojo路径
  type-aliases-package: com.prayerlaputa.week11.encrpyt_password.mapper
  configuration:
    #驼峰
    map-underscore-to-camel-case: true